name: C/C++ CI

on:
  push:
    branches: [ ibus ]
  pull_request:
    branches: [ ibus ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get install -y clang python pkg-config curl bzip2 unzip make libibus-1.0-dev libglib2.0-dev qtbase5-dev libgtk2.0-dev libxcb-xfixes0-dev python-six
        git -C src/third_party clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$GITHUB_WORKSPACE/src/third_party/depot_tools" >> $GITHUB_PATH
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive        
    - name: build
      run: |
        cd src
        python build_mozc.py gyp --target_platform=Linux
        python build_mozc.py build -c Release package
        cd ..
